public with sharing class VSDemoClass {
    public VSDemoClass() {

    }
    public integer add(integer a, integer b){
        return a+b;
    }

    public integer sub(integer a, integer b){
        return a-b;
    }

    public integer mul(integer a, integer b){
        return a*b;
    }

    public integer div(integer a, integer b){
        return a/b;
    }
    
    public void random(integer a, integer b){
        integer a1 = a * b;
        integer b1 = b * a;
        return a1+b1;
    }
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    
}